project:
  type: website
  render:
    - "*.qmd"
  resources:
    - js/dag-utils.js
    - img/
  preview:
    port: 7777

website:
  title: "DAGs"
  favicon: img/favicon.png
  navbar:
    left:
      - text: Confounders
        href: confounders.qmd
      - text: Mediators
        href: mediators.qmd
      - text: Colliders
        href: colliders.qmd

format:
  html:
    html-math-method: katex
    theme:
      - zephyr
      - css/styles.scss
      - brand
