project:
  type: website
  render:
    - "*.qmd"
  resources:
    - js/dag-utils.js
    - img/
  preview:
    port: 7777

execute:
  freeze: auto

website:
  title: "DAGs"
  favicon: img/favicon.png
  navbar:
    left:
      - text: "Interactive DAGs"
        menu:
        - text: Confounders
          href: confounders.qmd
        - text: Mediators
          href: mediators.qmd
        - text: Colliders
          href: colliders.qmd
      - text: "*do*-calculus"
        href: do-calculus.qmd
      - text: How to adjust
        href: adjustment.qmd

format:
  html:
    html-math-method: katex
    theme:
      - zephyr
      - css/styles.scss
      - brand
