project:
  type: website
  render:
    - "*.qmd"
  resources:
    - js/dag-utils.js
  preview:
    port: 7777

website:
  title: "Interactive DAGs"
  navbar:
    left:
      - text: Confounders
        href: confounders.qmd
      - text: Mediators
        href: mediators.qmd
      - text: Colliders
        href: colliders.qmd

format:
  html:
    theme:
      - zephyr
      - css/styles.scss
      - brand
